In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression


In [2]:
data=pd.read_csv('1.02. Multiple linear regression.csv')

In [3]:
data.head

<bound method NDFrame.head of      SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]>

In [4]:
data.head()

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3
2  1760  2.54           3
3  1685  2.74           3
4  1693  2.83           2

In [5]:
x=data[['SAT','Rand 1,2,3']]
y=data['GPA']

In [6]:
reg=LinearRegression()

In [7]:
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [9]:
reg.intercept_

0.29603261264909486

In [10]:
reg.score(x,y)

0.4066811952814285

### formula for adjusted r^2
$R^2_{adj.} = 1-(1-R^2)*\frac{n-1}{n-p-1}$

In [11]:
r2=reg.score(x,y)
n=x.shape[0]
p=x.shape[1]
adjusted=1-(1-r2)*(n-1)/(n-p-1)
adjusted

0.39203134825134023

In [12]:
 from sklearn.feature_selection import f_regression

In [13]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [16]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [17]:
reg_summary ['Coeffecients'] =reg.coef_

In [18]:
p=f_regression(x,y)[1]

In [19]:
p

array([7.19951844e-11, 6.76291372e-01])

In [20]:
reg_summary['p_values']=p.round(3)

In [21]:
reg_summary

Features  Coeffecients  p_values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676